### ISSUE TITLE
Xacro render launch substitution

### ISSUE THREAD

**Issue by emersonknapp** [robograph-project/planning#19]
Looks like commonly a `Command` substitution is used

https://docs.ros.org/en/jazzy/Tutorials/Intermediate/URDF/Using-Xacro-to-Clean-Up-a-URDF-File.html

I think we could shorten this so it's much clearer to users. like

```
node:
  param:
      - name: robot_description
        value: $(render-xacro $(find-package-share my_pkg)/urdf/my.urdf.xacro x:=y z:=foo) 
```
